"""The checks `gate` runs by default. Checks a package configures (caller lists, tolerance names, sentinel directories) join them through `gate`'s `checks`."""
const CHECKS = (
    Corpus(),
    ModuleBackEdges(),
    ModuleCycles(),
    ContractsPurity(),
    OwnerUniqueness(),
    ModulePiracy(),
    FileBackEdges(),
    FileSinkable(),
    Sinkable(),
    TupleReturns(),
    DeadCode(),
    BlanketExports(),
    StaleExports(),
    ReachesInternal(),
    PrivateImports(),
    DeclaredNames(),
    DeclaredModules(),
    DeclaredExtensions(),
    ForeignFields(),
    BoxedCaptures(),
    AbstractFields(),
    TypeBranches(),
    StorageOverloads(),
    ExpressionClones(),
    OneProducer(),
    CacheKeys(),
    CachedCalls(),
    DerivedReaders(),
)

